lib/rss_reader_web/router.ex
defmodule RssReaderWeb.Router do
  use RssReaderWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RssReaderWeb do
    pipe_through :browser

    get "/", PageController, :index

    get "/feeds", FeedController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", RssReaderWeb do
  #   pipe_through :api
  # end
end

lib/rss_reader/application.ex
defmodule RssReader.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      RssReader.Repo,
      RssReader.Feeds.SlurpSupervisor,
      # Start the endpoint when the application starts
      RssReaderWeb.Endpoint
      # Starts a worker by calling: RssReader.Worker.start_link(arg)
      # {RssReader.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: RssReader.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    RssReaderWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/rss_reader/feeds/feed.ex
defmodule RssReader.Feeds.Feed do
  use Ecto.Schema
  import Ecto.Changeset


  schema "feeds" do
    field :body, :string
    field :title, :string

    timestamps()
  end

  @doc false
  def changeset(feed, attrs) do
    feed
    |> cast(attrs, [:title, :body])
    |> validate_required([:title, :body])
  end
end

lib/rss_reader/feeds/feeds.ex
defmodule RssReader.Feeds do
  def all_stories() do
    RssReader.Feeds.Slurper.all_stories()
  end
end

lib/rss_reader/feeds/slurp_supervisor.ex
defmodule RssReader.Feeds.SlurpSupervisor do
  use Supervisor

  def start_link(arg) do
    Supervisor.start_link(__MODULE__, arg, name: __MODULE__)
  end

  # TODO: https://lorem-rss.herokuapp.com/
  @impl true
  def init(_arg) do
    IO.puts "Starting supervisor"
    children = [
      {RssReader.Feeds.Slurper, ["http://feeds.arstechnica.com/arstechnica/index/",
                                 "http://rss.nytimes.com/services/xml/rss/nyt/Science.xml",
                                 "https://lorem-rss.herokuapp.com/feed"]}
    ]

    Supervisor.init(children, strategy: :one_for_one)
  end
end

lib/rss_reader/feeds/slurper.ex
defmodule RssReader.Feeds.Slurper do
  use GenServer

  def start_link(state) do
    GenServer.start_link(__MODULE__, state, name: __MODULE__)
  end

  @impl true
  def init(urls) do
    IO.puts "Starting slurper"
    schedule_work

    stories = fetch_stories(urls)

    {:ok, %{urls: urls, stories: stories}}
  end

  # Client

  def all_stories() do
    GenServer.call(__MODULE__, :all_stories)
  end

  # Callbacks

  def handle_info(:work, state) do
    IO.puts "Doing work..."
    stories = fetch_stories(state.urls)

    schedule_work() # Reschedule once more
    {:noreply, %{state | stories: stories}}
  end

  def handle_call(:all_stories, _from, state) do
    {:reply, state.stories, state}
  end

  defp schedule_work() do
    Process.send_after(self(), :work, 60 * 1000) # In 2 hours
  end

  def fetch_stories(urls) when is_list(urls) do
    Enum.flat_map(urls, &fetch_stories(&1))
    |> Enum.sort_by(fn (t) -> t.updated end)
    |> Enum.reverse()
  end

  def fetch_stories(url) do
    %{body: body} = HTTPoison.get!(url)

    feed_data = ElixirFeedParser.parse(body)

    feed_data[:entries] |> Enum.map(fn (entry) ->
      {:ok, datetime} = Timex.parse(entry.updated, "{RFC1123}")

      entry
      |> Map.take(~w[author title content description updated]a)
      |> Map.update!(:content, fn (html) ->
        HtmlSanitizeEx.basic_html(html)
      end)
      |> Map.put(:rss_url, url)
      |> Map.put(:updated, datetime)
    end)
  end
end

lib/rss_reader/repo.ex
defmodule RssReader.Repo do
  use Ecto.Repo,
    otp_app: :rss_reader,
    adapter: Ecto.Adapters.Postgres
end

lib/rss_reader_web/controllers/feed_controller.ex
defmodule RssReaderWeb.FeedController do
  use RssReaderWeb, :controller

  alias RssReader.Feeds
  alias RssReader.Feeds.Feed

  def index(conn, _params) do
    stories = RssReader.Feeds.all_stories()
    render(conn, "index.html", stories: stories)
  end

  def show(conn, %{"id" => id}) do
    feed = Feeds.get_feed!(id)
    render(conn, "show.html", feed: feed)
  end
end

lib/rss_reader_web/controllers/page_controller.ex
defmodule RssReaderWeb.PageController do
  use RssReaderWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/rss_reader_web/views/error_view.ex
defmodule RssReaderWeb.ErrorView do
  use RssReaderWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/rss_reader_web/views/feed_view.ex
defmodule RssReaderWeb.FeedView do
  use RssReaderWeb, :view
end

lib/rss_reader_web/views/layout_view.ex
defmodule RssReaderWeb.LayoutView do
  use RssReaderWeb, :view
end

lib/rss_reader_web/views/page_view.ex
defmodule RssReaderWeb.PageView do
  use RssReaderWeb, :view
end

lib/rss_reader_web/templates/feed/edit.html.eex
<h1>Edit Feed</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.feed_path(@conn, :update, @feed)) %>

<span><%= link "Back", to: Routes.feed_path(@conn, :index) %></span>

lib/rss_reader_web/templates/feed/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :title %>
  <%= text_input f, :title %>
  <%= error_tag f, :title %>

  <%= label f, :body %>
  <%= textarea f, :body %>
  <%= error_tag f, :body %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/rss_reader_web/templates/feed/index.html.eex
<h1>Listing Feeds</h1>

<table>
  <thead>
    <tr>
      <th>RSS URL</th>
      <th>Updated</th>
      <th>Title</th>
      <th>Body</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for story <- @stories do %>
    <tr>
      <td><%= story.rss_url %></td>
      <td><%= inspect story.updated %></td>
      <td><%= story.title %></td>
      <td><%= raw story.content %></td>
    </tr>
<% end %>
  </tbody>
</table>

lib/rss_reader_web/templates/feed/new.html.eex
<h1>New Feed</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.feed_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.feed_path(@conn, :index) %></span>

lib/rss_reader_web/templates/feed/show.html.eex
<h1>Show Feed</h1>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @feed.title %>
  </li>

  <li>
    <strong>Body:</strong>
    <%= @feed.body %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.feed_path(@conn, :edit, @feed) %></span>
<span><%= link "Back", to: Routes.feed_path(@conn, :index) %></span>

lib/rss_reader_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>RssReader · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
          </ul>
        </nav>
        <a href="http://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/rss_reader_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h1>
  <p>A productive web framework that<br/>does not compromise speed and maintainability.</p>
</section>

<section class="row">
  <article class="column">
    <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.4/CHANGELOG.md">v1.4 Changelog</a>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>Help</h2>
    <ul>
      <li>
        <a href="https://elixirforum.com/c/phoenix-forum">Forum</a>
      </li>
      <li>
        <a href="https://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on Freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">Twitter @elixirphoenix</a>
      </li>
    </ul>
  </article>
</section>